### ISSUE TITLE
Feature request: Enable to configure delay to save

### ISSUE THREAD

**Issue by MissingUser** [seanh/gedit-smart-autosave#2]
I would like to be able to configure a differente delay before autosave instead of half a second. Maybe I am very slow writing because I have interferences while writing with saving procedure.
Some kind of option configurable to determinate half a second, a second... etc.
Thanks.

**Comment by seanh** [comment]
Hi, it's unlikely that an option will be added to `gedit-smart-autosave` since I no longer maintain this plugin. But you can edit the file at `.local/share/gedit/plugins/gedit-smart-autosave/smart_autosave/plugin.py` and change the `500` on [line 29](https://github.com/seanh/gedit-smart-autosave/blob/91bf14a29abb53054072d393276da1823edc3707/smart_autosave/plugin.py#L29) to however many milliseconds you want the delay to be
